package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import controller.DisplayPanel;
import model.*;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author xiaopu
 */
public class FireAlarmPanel extends javax.swing.JPanel {

    /**
     * Creates new form FireAlarmPanel
     * @param
     * @param user
     */
    public FireAlarmPanel(User user) {
        this.user = user;
        initComponents();
        user.getService().activeNumOfRooms = calNumOfActivatedRoom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        systemPanel = new javax.swing.JPanel();
        fireAlarmLabel = new javax.swing.JLabel();
        goBackButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        scheduleButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        DetailInfoTextField = new javax.swing.JTextField();
        DetailInfoLabel = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        roomRadioButton1 = new javax.swing.JRadioButton();
        roomRadioButton2 = new javax.swing.JRadioButton();
        roomRadioButton4 = new javax.swing.JRadioButton();
        roomRadioButton8 = new javax.swing.JRadioButton();
        roomRadioButton3 = new javax.swing.JRadioButton();
        roomRadioButton12 = new javax.swing.JRadioButton();
        roomRadioButton13 = new javax.swing.JRadioButton();
        roomRadioButton14 = new javax.swing.JRadioButton();
        roomRadioButton5 = new javax.swing.JRadioButton();
        roomRadioButton6 = new javax.swing.JRadioButton();
        roomRadioButton7 = new javax.swing.JRadioButton();
        roomRadioButton10 = new javax.swing.JRadioButton();
        roomRadioButton9 = new javax.swing.JRadioButton();
        roomRadioButton11 = new javax.swing.JRadioButton();
        sectionRadioButton1 = new javax.swing.JRadioButton();
        sectionRadioButton2 = new javax.swing.JRadioButton();
        sectionRadioButton3 = new javax.swing.JRadioButton();
        sectionRadioButton4 = new javax.swing.JRadioButton();
        TriggerSectionButton1 = new javax.swing.JButton();
        TriggerSectionButton2 = new javax.swing.JButton();
        TriggerSectionButton3 = new javax.swing.JButton();
        TriggerSectionButton4 = new javax.swing.JButton();
        DetailInfoTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();

        // start here
        setUpPanel = new SetUpPanel();
        simulatePanel = new SimulatePanel();

        fireAlarmService = new FireAlarmService("fireAlarmService");
        //temperatureSensor = new TemperatureSensor();
        user.setService(fireAlarmService);
        //user.setSensor(temperatureSensor);

        fireAlarmService.sensorList = new ArrayList<>();
        sectionButtonList = new ArrayList<>();
        roomButtonList = new ArrayList<>();
        //end

        fireAlarmLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fireAlarmLabel.setText("FireAlarm System");

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        scheduleButton.setText("schedule");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout systemPanelLayout = new javax.swing.GroupLayout(systemPanel);
        systemPanel.setLayout(systemPanelLayout);
        systemPanelLayout.setHorizontalGroup(
                systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(systemPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fireAlarmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 58, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, systemPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(scheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
        );
        systemPanelLayout.setVerticalGroup(
                systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(systemPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(fireAlarmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(scheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
        );

        DetailInfoLabel.setText("Detail Information");

        DetailInfoTextArea.setColumns(20);
        DetailInfoTextArea.setRows(5);
        jScrollPane1.setViewportView(DetailInfoTextArea);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
                tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DetailInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(278, 278, 278))
                        .addGroup(tablePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
                tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tablePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DetailInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );

        roomRadioButton1.setText("room1");
        roomRadioButton2.setText("room2");
        roomRadioButton3.setText("room3");
        roomRadioButton4.setText("room4");
        roomRadioButton5.setText("room5");
        roomRadioButton6.setText("room6");
        roomRadioButton7.setText("room7");
        roomRadioButton8.setText("room8");
        roomRadioButton9.setText("room9");
        roomRadioButton10.setText("room10");
        roomRadioButton11.setText("room11");
        roomRadioButton12.setText("room12");
        roomRadioButton13.setText("room13");
        roomRadioButton14.setText("room14");

        sectionRadioButton1.setText("section1");
        sectionRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionRadioButton1ActionPerformed(evt);
            }
        });

        sectionRadioButton2.setText("section2");
        sectionRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionRadioButton2ActionPerformed(evt);
            }
        });

        sectionRadioButton3.setText("section3");
        sectionRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionRadioButton3ActionPerformed(evt);
            }
        });

        sectionRadioButton4.setText("section4");
        sectionRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setUpPanelLayout = new javax.swing.GroupLayout(setUpPanel);
        setUpPanel.setLayout(setUpPanelLayout);
        setUpPanelLayout.setHorizontalGroup(
                setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(214, 214, 214)
                                                .addComponent(roomRadioButton2))
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(148, 148, 148)
                                                .addComponent(sectionRadioButton3))
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(159, 159, 159)
                                                .addComponent(sectionRadioButton1))
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(roomRadioButton3)))
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                                                .addComponent(roomRadioButton6)
                                                                                .addGap(131, 131, 131))
                                                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                                                .addComponent(roomRadioButton4)
                                                                                .addGap(52, 52, 52)
                                                                                .addComponent(roomRadioButton8)
                                                                                .addGap(215, 215, 215)))
                                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(roomRadioButton5)
                                                                        .addComponent(roomRadioButton7))
                                                                .addGap(35, 35, 35))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(sectionRadioButton4)
                                                                        .addComponent(sectionRadioButton2))
                                                                .addGap(140, 140, 140))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                                                                .addComponent(roomRadioButton13)
                                                                .addGap(75, 75, 75)
                                                                .addComponent(roomRadioButton14)
                                                                .addGap(54, 54, 54))))
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(roomRadioButton10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(roomRadioButton12)
                                                .addGap(249, 249, 249))))
                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addComponent(roomRadioButton9)
                                                .addGap(129, 129, 129)
                                                .addComponent(roomRadioButton11))
                                        .addComponent(roomRadioButton1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setUpPanelLayout.setVerticalGroup(
                setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(roomRadioButton7)
                                                        .addComponent(roomRadioButton6)
                                                        .addComponent(roomRadioButton1))
                                                .addGap(22, 22, 22)
                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(sectionRadioButton2)
                                                        .addComponent(sectionRadioButton1)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(roomRadioButton2)
                                                .addGap(56, 56, 56)))
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(roomRadioButton5)
                                                        .addComponent(roomRadioButton3)))
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(roomRadioButton8)
                                                        .addComponent(roomRadioButton4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sectionRadioButton3)
                                        .addComponent(roomRadioButton12)
                                        .addComponent(roomRadioButton10))
                                .addComponent(sectionRadioButton4)
                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(setUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(roomRadioButton11)
                                                                        .addComponent(roomRadioButton9)))
                                                        .addGroup(setUpPanelLayout.createSequentialGroup()
                                                                .addGap(49, 49, 49)
                                                                .addComponent(roomRadioButton13)))
                                                .addGap(51, 51, 51))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setUpPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(roomRadioButton14)
                                                .addGap(37, 37, 37))))
        );

        jTabbedPane.addTab("Set Up", setUpPanel);

        TriggerSectionButton1.setText("Trigger_Section1");
        TriggerSectionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriggerSectionButton1ActionPerformed(evt);
            }
        });

        TriggerSectionButton2.setText("Trigger_Section2");
        TriggerSectionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriggerSectionButton2ActionPerformed(evt);
            }
        });

        TriggerSectionButton3.setText("Trigger_Section3");
        TriggerSectionButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriggerSectionButton3ActionPerformed(evt);
            }
        });

        TriggerSectionButton4.setText("Trigger_Section4");
        TriggerSectionButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriggerSectionButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout simulationPanelLayout = new javax.swing.GroupLayout(simulatePanel);
        simulatePanel.setLayout(simulationPanelLayout);
        simulationPanelLayout.setHorizontalGroup(
                simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulationPanelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(simulationPanelLayout.createSequentialGroup()
                                                .addComponent(TriggerSectionButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                                                .addComponent(TriggerSectionButton2))
                                        .addGroup(simulationPanelLayout.createSequentialGroup()
                                                .addComponent(TriggerSectionButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TriggerSectionButton4)))
                                .addGap(139, 139, 139))
        );
        simulationPanelLayout.setVerticalGroup(
                simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(simulationPanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TriggerSectionButton1)
                                        .addComponent(TriggerSectionButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                                .addGroup(simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulationPanelLayout.createSequentialGroup()
                                                .addComponent(TriggerSectionButton3)
                                                .addGap(94, 94, 94))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulationPanelLayout.createSequentialGroup()
                                                .addComponent(TriggerSectionButton4)
                                                .addGap(108, 108, 108))))
        );

        jTabbedPane.addTab("Simulation", simulatePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(systemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTabbedPane)
                                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(systemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
        );

        //start from here
        getRoomButtonList();
        getSectionButtonList();

    }// </editor-fold>

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel().getCards().show(DisplayPanel.getDisplayPanel(), "mainPanel");
    }

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //bug here
        ScheduleTimePanel scheduleTimePanel = new ScheduleTimePanel();
        scheduleTimePanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        scheduleTimePanel.setVisible(true);
        startButtonActionPerformed(evt);
    }


    //a list to store the selected sections
    // a list to store the selected rooms
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("*****");
        for(int i =0; i < calNumOfActivatedRoom(); i++){
                Sensor sensor = (Sensor) DetectorFactory.getSensor("Fire Alarm");
                sensor.setVariable();
                //sensor.setBreakIn(false);
                sensor.setSensorStatus(true);
                sensor.setSensorID(i + 1);
                sensor.setLocation("Area");
                sensor.displaySensorInfo();
        }
        for (int i = 0; i < sectionButtonList.size(); i++) {
            if(sectionButtonList.get(i).isSelected()) {
                Section section = fireAlarmService.getSectionId(i);

                DetailInfoTextArea.append("Section" + section.getSectionId() + " has been selected and sensor has been activated.\n" );

            }
        }

        for (int i = 0; i < roomButtonList.size(); i++) {
            if(roomButtonList.get(i).isSelected()) {
                Room room = fireAlarmService.getRoomId(i);
                room.isSelected = true;
                DetailInfoTextArea.append("room" + room.getRoomId() + " has been selected and sensor has been activated.\n" );

            }
        }
    }

    private void TriggerSectionButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        FireAlarm.getInstance();
        if (sectionRadioButton1.isSelected()) {
            AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
            alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            alarmPanel.setVisible(true);
        } else {
            for (Room room : fireAlarmService.getRoomList1()) {
                if (room.isSelected) {
                    AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
                    alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    alarmPanel.setVisible(true);
                    break;
                }
            }
        }
    }

    private void TriggerSectionButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        FireAlarm.getInstance();
        if (sectionRadioButton2.isSelected()) {
            AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
            alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            alarmPanel.setVisible(true);
        } else {
            for (Room room : fireAlarmService.getRoomList2()) {
                if (room.isSelected) {
                    System.out.println(room.isSelected);
                    AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
                    alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    alarmPanel.setVisible(true);
                    break;
                }
            }
        }
    }

    private void TriggerSectionButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        FireAlarm.getInstance();
        if (sectionRadioButton3.isSelected()) {
            AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
            alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            alarmPanel.setVisible(true);
        } else {
            for (Room room : fireAlarmService.getRoomList3()) {
                if (room.isSelected) {
                    AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
                    alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    alarmPanel.setVisible(true);
                    break;
                }
            }
        }
    }

    private void TriggerSectionButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        FireAlarm.getInstance();
        if (sectionRadioButton4.isSelected()) {
            AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
            alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            alarmPanel.setVisible(true);
        } else {
            for (Room room : fireAlarmService.getRoomList4()) {
                if (room.isSelected) {
                    AlarmPanel alarmPanel = new AlarmPanel("fireAlarm.png", user);
                    alarmPanel.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    alarmPanel.setVisible(true);
                    break;
                }
            }
        }
    }

    //add sensors here
    private void sectionRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (sectionRadioButton1.isSelected()) {
            roomRadioButton1.setSelected(true);
            roomRadioButton2.setSelected(true);
            roomRadioButton3.setSelected(true);
            roomRadioButton4.setSelected(true);
            /*for (int i = 0; i < 4; i++) {
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
            }*/

        } else {
            roomRadioButton1.setSelected(false);
            roomRadioButton2.setSelected(false);
            roomRadioButton3.setSelected(false);
            roomRadioButton4.setSelected(false);

        }
    }

    private void sectionRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (sectionRadioButton2.isSelected()) {
            roomRadioButton5.setSelected(true);
            roomRadioButton6.setSelected(true);
            roomRadioButton7.setSelected(true);
            roomRadioButton8.setSelected(true);
            /*for (int i = 0; i < 4; i++) {
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
            }*/
        } else {
            roomRadioButton5.setSelected(false);
            roomRadioButton6.setSelected(false);
            roomRadioButton7.setSelected(false);
            roomRadioButton8.setSelected(false);

        }
    }

    private void sectionRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (sectionRadioButton3.isSelected()) {
            roomRadioButton9.setSelected(true);
            roomRadioButton10.setSelected(true);
            roomRadioButton11.setSelected(true);
            /*for (int i = 0; i < 4; i++) {
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
            }*/
        } else {
            roomRadioButton9.setSelected(false);
            roomRadioButton10.setSelected(false);
            roomRadioButton11.setSelected(false);

        }
    }

    private void sectionRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (sectionRadioButton4.isSelected()) {
            roomRadioButton12.setSelected(true);
            roomRadioButton13.setSelected(true);
            roomRadioButton14.setSelected(true);
            /*for (int i = 0; i < 4; i++) {
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
                fireAlarmService.sensorList.add(new TemperatureSensor());
            }*/
        } else {
            roomRadioButton12.setSelected(false);
            roomRadioButton13.setSelected(false);
            roomRadioButton14.setSelected(false);

        }
    }



    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea DetailInfoTextArea;
    private javax.swing.JLabel DetailInfoLabel;
    private javax.swing.JTextField DetailInfoTextField;
    private javax.swing.JButton TriggerSectionButton1;
    private javax.swing.JButton TriggerSectionButton2;
    private javax.swing.JButton TriggerSectionButton3;
    private javax.swing.JButton TriggerSectionButton4;
    private javax.swing.JButton goBackButton;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JRadioButton roomRadioButton10;
    private javax.swing.JRadioButton roomRadioButton11;
    private javax.swing.JRadioButton roomRadioButton12;
    private javax.swing.JRadioButton roomRadioButton13;
    private javax.swing.JRadioButton roomRadioButton14;
    private javax.swing.JRadioButton roomRadioButton1;
    private javax.swing.JRadioButton roomRadioButton2;
    private javax.swing.JRadioButton roomRadioButton3;
    private javax.swing.JRadioButton roomRadioButton4;
    private javax.swing.JRadioButton roomRadioButton5;
    private javax.swing.JRadioButton roomRadioButton6;
    private javax.swing.JRadioButton roomRadioButton7;
    private javax.swing.JRadioButton roomRadioButton8;
    private javax.swing.JRadioButton roomRadioButton9;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JRadioButton sectionRadioButton1;
    private javax.swing.JRadioButton sectionRadioButton2;
    private javax.swing.JRadioButton sectionRadioButton3;
    private javax.swing.JRadioButton sectionRadioButton4;
    private javax.swing.JLabel fireAlarmLabel;
    //private javax.swing.JPanel setUpPanel;
    //private javax.swing.JPanel simulationPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel systemPanel;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration

    //start from here
    private class SetUpPanel extends JPanel {
        private BufferedImage image = FileUtil.getImageWithName("buildingLayout.jpg");
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, this);
        }
    }
    private class SimulatePanel extends JPanel {
        private BufferedImage image = FileUtil.getImageWithName("buildingLayout.jpg");
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, this);
        }
    }

    private void getSectionButtonList() {
        sectionButtonList.add(sectionRadioButton1);
        sectionButtonList.add(sectionRadioButton2);
        sectionButtonList.add(sectionRadioButton3);
        sectionButtonList.add(sectionRadioButton4);
    }

    private void getRoomButtonList() {
        roomButtonList.add(roomRadioButton1);
        roomButtonList.add(roomRadioButton2);
        roomButtonList.add(roomRadioButton3);
        roomButtonList.add(roomRadioButton4);
        roomButtonList.add(roomRadioButton5);
        roomButtonList.add(roomRadioButton6);
        roomButtonList.add(roomRadioButton7);
        roomButtonList.add(roomRadioButton8);
        roomButtonList.add(roomRadioButton9);
        roomButtonList.add(roomRadioButton10);
        roomButtonList.add(roomRadioButton11);
        roomButtonList.add(roomRadioButton12);
        roomButtonList.add(roomRadioButton13);
        roomButtonList.add(roomRadioButton14);

    }

    private int calNumOfActivatedRoom() {
        int num = 0;
        for (int i = 0; i < roomButtonList.size(); i++) {
            if(roomButtonList.get(i).isSelected()) {
                num++;
            }
        }
        return num;
    }

    private User user;
    private Service fireAlarmService;
    //private Sensor temperatureSensor;
    private SetUpPanel setUpPanel;
    private SimulatePanel simulatePanel;
    private List<JRadioButton> sectionButtonList;
    private List<JRadioButton> roomButtonList;

}
