package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import controller.DisplayPanel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author xiaopu
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     * @param
     */
    public MainPanel() {
        setLayout(new CardLayout());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        securityButton = new javax.swing.JButton();
        fireAlarmButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 750));
        setSize(new java.awt.Dimension(1200, 750));

        securityButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        securityButton.setText("Security System ");
        securityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityButtonActionPerformed(evt);
            }
        });

        fireAlarmButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        fireAlarmButton.setText("Fire Alarm System");
        fireAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireAlarmButtonActionPerformed(evt);
            }
        });

        userButton.setText("User");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("go back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(securityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(fireAlarmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fireAlarmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel().getCards().show(DisplayPanel.getDisplayPanel(), "signInPanel");

    }//GEN-LAST:event_goBackButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel().getCards().show(DisplayPanel.getDisplayPanel(), "userPanel");


    }//GEN-LAST:event_userButtonActionPerformed

    private void fireAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireAlarmButtonActionPerformed
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel().getCards().show(DisplayPanel.getDisplayPanel(), "fireAlarmPanel");

    }//GEN-LAST:event_fireAlarmButtonActionPerformed

    private void securityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityButtonActionPerformed
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel().getCards().show(DisplayPanel.getDisplayPanel(), "securityPanel");

    }//GEN-LAST:event_securityButtonActionPerformed

    public static MainPanel getMainPanel() {
        if (mainPanel == null) {
            mainPanel = new MainPanel();
        }
        return mainPanel;
    }

    public GroupLayout getLayout() {
        return layout;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GroupLayout layout;
    private static MainPanel mainPanel;
    private javax.swing.JButton fireAlarmButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton securityButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
